version: 2.1
jobs:

  github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "`awk '/##.*/{n++;next};n==1;n==2{exit}' CHANGELOG.md`" -delete ${CIRCLE_TAG} ./CHANGELOG.md

  tests:
    docker:
    - image: node:20
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17 for DynamoDB Local
          command: |
            apt-get update
            apt-get install -y openjdk-17-jre-headless
            java -version
      - restore_cache:
          keys:
            - npm-deps-v1-{{ checksum "package-lock.json" }}
            - npm-deps-v1-
      - run: npm install
      - run:
          name: Install DynamoDB Local
          command: npm run dynamodb:install
      - save_cache:
          key: npm-deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - .dynamodb
      - run: npm run test

  lint:
    docker:
    - image: node:20-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-v1-{{ checksum "package-lock.json" }}
            - npm-deps-v1-
      - run: npm install
      - save_cache:
          key: npm-deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint

workflows:
  version: 2
  default:
    jobs:
      - tests
      - lint
      - github-release:
          context: github
          filters:
            tags:
              only: /^v\d+\.\d+\..*/
            branches:
              ignore: /.*/
